version: "2"
services:
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: le
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${CONFIG_DIR}/letsencrypt:/config
    restart: always
    depends_on:
      - sonarr
    environment:
      PUID: ${ID}
      PGID: ${ID}
      EMAIL: ${MAIL}
      URL: ${DOMAIN}
      DHLEVEL: "4096"
      TZ: ${TZ}
      HTTPVAL: "true"
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    ports:
      - '9091:9091'
      - '51413:51413'
      - '51413:51413/udp'
    environment:
      PGID: ${ID}
      PUID: ${ID}
      TZ: ${TZ}
    volumes:
      - ${CONFIG_DIR}/transmission:/config
      - ${DOWNLOAD_DIR}:/downloads
      - ${TRANSMISSION_WATCH_DIR}:/watch
    restart: always
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    depends_on:
      - transmission
    ports:
      - '8989:8989'
    volumes:
      - ${CONFIG_DIR}/sonarr:/config
      - ${MEDIA_DIR}:/mediabox
      - /etc/localtime:/etc/localtime:ro
    environment:
      PGID: ${ID}
      PUID: ${ID}
      TZ: ${TZ}
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    depends_on:
      - transmission
    ports:
      - '7878:7878'
    volumes:
      - ${CONFIG_DIR}/radarr:/config
      - ${MEDIA_DIR}:/mediabox
      - /etc/localtime:/etc/localtime:ro
    environment:
      PGID: ${ID}
      PUID: ${ID}
      TZ: ${TZ}
    restart: unless-stopped
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    ports:
      - '9117:9117'
    volumes:
      - ${CONFIG_DIR}/jackett:/config
      - ${TRANSMISSION_WATCH_DIR}:/downloads
      - /etc/localtime:/etc/localtime:ro
    environment:
      PGID: ${ID}
      PUID: ${ID}
      TZ: ${TZ}
    restart: unless-stopped
  emby:
    image: nvllsvm/emby-unlocked
    container_name: emby
    ports:
      - '8096:8096'
    environment:
      APP_UID: ${ID}
      APP_GID: ${ID}
      APP_USER: "mediabox"
      TZ: ${TZ}
    volumes:
      - ${CONFIG_DIR}/emby:/config
      - ${MEDIA_DIR}:/media
      - /etc/localtime:/etc/localtime:ro
    restart: always
  ombi:
    image: linuxserver/ombi:latest
    container_name: ombi
    ports:
      - '3579:3579'
    environment:
      PGID: ${ID}
      PUID: ${ID}
      TZ: ${TZ}
    volumes:
      - ${CONFIG_DIR}/ombi:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
  organizr:
    image: lsiocommunity/organizr
    container_name: organizr
    ports:
      - '81:80'
    environment:
      PGID: ${ID}
      PUID: ${ID}
      TZ: ${TZ}
    volumes:
      - ${CONFIG_DIR}/organizr:/config
    restart: always
  headphones:
    image: linuxserver/headphones
    container_name: headphones
    ports:
      - '8181:8181'
    volumes:
      - ${CONFIG_DIR}/headphones:/config
      - ${MEDIA_DIR}:/mediabox
    environment:
      PGID: ${ID}
      PUID: ${ID}
      TZ: ${TZ}
    restart: always
